// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainingSimulation.Data;

#nullable disable

namespace TrainingSimulation.Migrations
{
    [DbContext(typeof(TrainingSimulationDbContext))]
    [Migration("20241009103253_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("TrainingSimulation.Data.Soldier", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrainingInfo")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Soldiers");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Country = "United States",
                            Name = "John Doe",
                            Rank = "Sergeant",
                            TrainingInfo = "Training info"
                        },
                        new
                        {
                            Id = 2L,
                            Country = "Russia",
                            Name = "Maria Ivanova",
                            Rank = "Lieutenant",
                            TrainingInfo = "Training info"
                        },
                        new
                        {
                            Id = 3L,
                            Country = "Japan",
                            Name = "Akira Tanaka",
                            Rank = "Captain",
                            TrainingInfo = "Training info"
                        },
                        new
                        {
                            Id = 4L,
                            Country = "Saudi Arabia",
                            Name = "Ahmed Al-Farsi",
                            Rank = "Major",
                            TrainingInfo = "Training info"
                        },
                        new
                        {
                            Id = 5L,
                            Country = "Mexico",
                            Name = "Carlos Sanchez",
                            Rank = "Corporal",
                            TrainingInfo = "Training info"
                        },
                        new
                        {
                            Id = 6L,
                            Country = "France",
                            Name = "Pierre Dupont",
                            Rank = "Private",
                            TrainingInfo = "Training info"
                        },
                        new
                        {
                            Id = 7L,
                            Country = "Egypt",
                            Name = "Hassan Abdallah",
                            Rank = "Lieutenant",
                            TrainingInfo = "Training info"
                        },
                        new
                        {
                            Id = 8L,
                            Country = "China",
                            Name = "Chen Wei",
                            Rank = "Colonel",
                            TrainingInfo = "Training info"
                        },
                        new
                        {
                            Id = 9L,
                            Country = "Ireland",
                            Name = "Liam O'Connor",
                            Rank = "Sergeant",
                            TrainingInfo = "Training info"
                        },
                        new
                        {
                            Id = 10L,
                            Country = "India",
                            Name = "Rajesh Patel",
                            Rank = "Major",
                            TrainingInfo = "Training info"
                        },
                        new
                        {
                            Id = 11L,
                            Country = "Russia",
                            Name = "Elena Petrova",
                            Rank = "Captain",
                            TrainingInfo = "Training info"
                        },
                        new
                        {
                            Id = 12L,
                            Country = "Ghana",
                            Name = "Kofi Mensah",
                            Rank = "Private",
                            TrainingInfo = "Training info"
                        },
                        new
                        {
                            Id = 13L,
                            Country = "Spain",
                            Name = "Miguel Ramirez",
                            Rank = "Lieutenant",
                            TrainingInfo = "Training info"
                        },
                        new
                        {
                            Id = 14L,
                            Country = "Germany",
                            Name = "Thomas Müller",
                            Rank = "Sergeant",
                            TrainingInfo = "Training info"
                        },
                        new
                        {
                            Id = 15L,
                            Country = "Brazil",
                            Name = "Paulo Oliveira",
                            Rank = "Corporal",
                            TrainingInfo = "Training info"
                        },
                        new
                        {
                            Id = 16L,
                            Country = "Italy",
                            Name = "Isabella Rossi",
                            Rank = "Lieutenant",
                            TrainingInfo = "Training info"
                        },
                        new
                        {
                            Id = 17L,
                            Country = "Pakistan",
                            Name = "Abdul Rahman",
                            Rank = "Captain",
                            TrainingInfo = "Training info"
                        },
                        new
                        {
                            Id = 18L,
                            Country = "Japan",
                            Name = "Satoshi Nakamura",
                            Rank = "Sergeant",
                            TrainingInfo = "Training info"
                        },
                        new
                        {
                            Id = 19L,
                            Country = "Saudi Arabia",
                            Name = "Zainab Al-Hassan",
                            Rank = "Major",
                            TrainingInfo = "Training info"
                        },
                        new
                        {
                            Id = 20L,
                            Country = "United Kingdom",
                            Name = "Robert Johnson",
                            Rank = "Corporal",
                            TrainingInfo = "Training info"
                        },
                        new
                        {
                            Id = 21L,
                            Country = "Argentina",
                            Name = "Jorge Gonzalez",
                            Rank = "Private",
                            TrainingInfo = "Training info"
                        },
                        new
                        {
                            Id = 22L,
                            Country = "Nigeria",
                            Name = "Amina Ali",
                            Rank = "Lieutenant",
                            TrainingInfo = "Training info"
                        },
                        new
                        {
                            Id = 23L,
                            Country = "South Korea",
                            Name = "David Kim",
                            Rank = "Sergeant",
                            TrainingInfo = "Training info"
                        },
                        new
                        {
                            Id = 24L,
                            Country = "United Arab Emirates",
                            Name = "Yousef Nasser",
                            Rank = "Colonel",
                            TrainingInfo = "Training info"
                        },
                        new
                        {
                            Id = 25L,
                            Country = "Germany",
                            Name = "Hans Schmidt",
                            Rank = "Major",
                            TrainingInfo = "Training info"
                        },
                        new
                        {
                            Id = 26L,
                            Country = "Brazil",
                            Name = "Luciana Silva",
                            Rank = "Lieutenant",
                            TrainingInfo = "Training info"
                        },
                        new
                        {
                            Id = 27L,
                            Country = "Poland",
                            Name = "Daniel Novak",
                            Rank = "Captain",
                            TrainingInfo = "Training info"
                        },
                        new
                        {
                            Id = 28L,
                            Country = "Egypt",
                            Name = "Fatima Mohamed",
                            Rank = "Private",
                            TrainingInfo = "Training info"
                        },
                        new
                        {
                            Id = 29L,
                            Country = "Sweden",
                            Name = "Sebastian Berg",
                            Rank = "Corporal",
                            TrainingInfo = "Training info"
                        },
                        new
                        {
                            Id = 30L,
                            Country = "Morocco",
                            Name = "Leila El-Hadad",
                            Rank = "Lieutenant",
                            TrainingInfo = "Training info"
                        });
                });

            modelBuilder.Entity("TrainingSimulation.Data.SoldierLocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<long>("SoldierId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SoldierId");

                    b.ToTable("SoldierLocations");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Latitude = 47.854450092316140m,
                            Longitude = 29.52004895912160m,
                            SoldierId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Latitude = -81.5945499692995860m,
                            Longitude = 80.705906462651040m,
                            SoldierId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            Latitude = 47.452451176406700m,
                            Longitude = 19.441644717833280m,
                            SoldierId = 2L
                        },
                        new
                        {
                            Id = 4L,
                            Latitude = -11.873775657593340m,
                            Longitude = -144.8039289875823000m,
                            SoldierId = 2L
                        },
                        new
                        {
                            Id = 5L,
                            Latitude = -12.650158787296320m,
                            Longitude = -147.7167384365849160m,
                            SoldierId = 3L
                        },
                        new
                        {
                            Id = 6L,
                            Latitude = 27.215154100837620m,
                            Longitude = 136.478167890174720m,
                            SoldierId = 3L
                        },
                        new
                        {
                            Id = 7L,
                            Latitude = 63.717301751111280m,
                            Longitude = 151.151648107140720m,
                            SoldierId = 4L
                        },
                        new
                        {
                            Id = 8L,
                            Latitude = 34.62999456716640m,
                            Longitude = 52.885107805547160m,
                            SoldierId = 4L
                        },
                        new
                        {
                            Id = 9L,
                            Latitude = -67.342986991076580m,
                            Longitude = -87.349896673826760m,
                            SoldierId = 5L
                        },
                        new
                        {
                            Id = 10L,
                            Latitude = 85.689737806192020m,
                            Longitude = 159.383973893060160m,
                            SoldierId = 5L
                        },
                        new
                        {
                            Id = 11L,
                            Latitude = 1.364295885852060m,
                            Longitude = -167.1891258241598040m,
                            SoldierId = 6L
                        },
                        new
                        {
                            Id = 12L,
                            Latitude = 51.152782676153580m,
                            Longitude = -4.436196363562320m,
                            SoldierId = 6L
                        },
                        new
                        {
                            Id = 13L,
                            Latitude = -78.0640152052077720m,
                            Longitude = 33.533475125273640m,
                            SoldierId = 7L
                        },
                        new
                        {
                            Id = 14L,
                            Latitude = -17.631888985770120m,
                            Longitude = -29.043942845110920m,
                            SoldierId = 7L
                        },
                        new
                        {
                            Id = 15L,
                            Latitude = 68.002710132734640m,
                            Longitude = 54.942339205574280m,
                            SoldierId = 8L
                        },
                        new
                        {
                            Id = 16L,
                            Latitude = 73.256002529843880m,
                            Longitude = 25.551524205843840m,
                            SoldierId = 8L
                        },
                        new
                        {
                            Id = 17L,
                            Latitude = -33.960915965910960m,
                            Longitude = -129.587510037946320m,
                            SoldierId = 9L
                        },
                        new
                        {
                            Id = 18L,
                            Latitude = -61.714803544043040m,
                            Longitude = 159.240163294463040m,
                            SoldierId = 9L
                        },
                        new
                        {
                            Id = 19L,
                            Latitude = 58.528387389850740m,
                            Longitude = 136.052918259020640m,
                            SoldierId = 10L
                        },
                        new
                        {
                            Id = 20L,
                            Latitude = 17.655713830423440m,
                            Longitude = 106.359641055239760m,
                            SoldierId = 10L
                        },
                        new
                        {
                            Id = 21L,
                            Latitude = 12.485057182610040m,
                            Longitude = 51.712722917395560m,
                            SoldierId = 11L
                        },
                        new
                        {
                            Id = 22L,
                            Latitude = -0.953918749930500m,
                            Longitude = -51.020895172372920m,
                            SoldierId = 11L
                        },
                        new
                        {
                            Id = 23L,
                            Latitude = -63.14481135772020m,
                            Longitude = -165.9675961732638960m,
                            SoldierId = 12L
                        },
                        new
                        {
                            Id = 24L,
                            Latitude = 23.294308230335700m,
                            Longitude = 124.735404322236960m,
                            SoldierId = 12L
                        },
                        new
                        {
                            Id = 25L,
                            Latitude = -63.228416688403920m,
                            Longitude = 167.746617067019400m,
                            SoldierId = 13L
                        },
                        new
                        {
                            Id = 26L,
                            Latitude = 79.915385224240920m,
                            Longitude = 106.090113238595280m,
                            SoldierId = 13L
                        },
                        new
                        {
                            Id = 27L,
                            Latitude = -38.835613316917440m,
                            Longitude = -29.574693946662480m,
                            SoldierId = 14L
                        },
                        new
                        {
                            Id = 28L,
                            Latitude = 44.636086429724160m,
                            Longitude = -29.84804542956240m,
                            SoldierId = 14L
                        },
                        new
                        {
                            Id = 29L,
                            Latitude = -2.850695199591480m,
                            Longitude = 11.853348314089320m,
                            SoldierId = 15L
                        },
                        new
                        {
                            Id = 30L,
                            Latitude = -88.52602433791677840m,
                            Longitude = 169.231598076524040m,
                            SoldierId = 15L
                        },
                        new
                        {
                            Id = 31L,
                            Latitude = 26.541958270638240m,
                            Longitude = 71.582114742033960m,
                            SoldierId = 16L
                        },
                        new
                        {
                            Id = 32L,
                            Latitude = 35.486624048112900m,
                            Longitude = -143.774961311543040m,
                            SoldierId = 16L
                        },
                        new
                        {
                            Id = 33L,
                            Latitude = -42.738774289996320m,
                            Longitude = 84.388142404588320m,
                            SoldierId = 17L
                        },
                        new
                        {
                            Id = 34L,
                            Latitude = -88.4476389143974860m,
                            Longitude = -96.472079458450560m,
                            SoldierId = 17L
                        },
                        new
                        {
                            Id = 35L,
                            Latitude = -8.673818696902440m,
                            Longitude = 73.203705805776480m,
                            SoldierId = 18L
                        },
                        new
                        {
                            Id = 36L,
                            Latitude = 53.564601290399280m,
                            Longitude = 89.70346803054240m,
                            SoldierId = 18L
                        },
                        new
                        {
                            Id = 37L,
                            Latitude = 17.298280028354580m,
                            Longitude = 51.047936495663400m,
                            SoldierId = 19L
                        },
                        new
                        {
                            Id = 38L,
                            Latitude = -86.0348015067389760m,
                            Longitude = -19.203903314885880m,
                            SoldierId = 19L
                        },
                        new
                        {
                            Id = 39L,
                            Latitude = 86.686700902341660m,
                            Longitude = 42.846353730278640m,
                            SoldierId = 20L
                        },
                        new
                        {
                            Id = 40L,
                            Latitude = -30.054701986498980m,
                            Longitude = -69.31293996716280m,
                            SoldierId = 20L
                        },
                        new
                        {
                            Id = 41L,
                            Latitude = 22.843063394019900m,
                            Longitude = 86.129213350067280m,
                            SoldierId = 21L
                        },
                        new
                        {
                            Id = 42L,
                            Latitude = 65.422919534990580m,
                            Longitude = -84.803386941649080m,
                            SoldierId = 21L
                        },
                        new
                        {
                            Id = 43L,
                            Latitude = -89.72950146171317640m,
                            Longitude = -18.782459546300280m,
                            SoldierId = 22L
                        },
                        new
                        {
                            Id = 44L,
                            Latitude = 17.162425466124660m,
                            Longitude = 92.971175372159400m,
                            SoldierId = 22L
                        },
                        new
                        {
                            Id = 45L,
                            Latitude = 0.573137919128700m,
                            Longitude = 95.061045380473440m,
                            SoldierId = 23L
                        },
                        new
                        {
                            Id = 46L,
                            Latitude = -34.16410059681780m,
                            Longitude = 79.939911937182480m,
                            SoldierId = 23L
                        },
                        new
                        {
                            Id = 47L,
                            Latitude = 0.255067614513900m,
                            Longitude = 82.066298030024040m,
                            SoldierId = 24L
                        },
                        new
                        {
                            Id = 48L,
                            Latitude = 15.582000522857940m,
                            Longitude = 135.884040964821000m,
                            SoldierId = 24L
                        },
                        new
                        {
                            Id = 49L,
                            Latitude = -59.77441274290020m,
                            Longitude = 32.726911377077640m,
                            SoldierId = 25L
                        },
                        new
                        {
                            Id = 50L,
                            Latitude = 80.244994051024380m,
                            Longitude = 3.123086725185840m,
                            SoldierId = 25L
                        },
                        new
                        {
                            Id = 51L,
                            Latitude = -26.985265815012120m,
                            Longitude = -149.9072345731798920m,
                            SoldierId = 26L
                        },
                        new
                        {
                            Id = 52L,
                            Latitude = 78.749286274380240m,
                            Longitude = -133.618863896655120m,
                            SoldierId = 26L
                        },
                        new
                        {
                            Id = 53L,
                            Latitude = -29.941901687895840m,
                            Longitude = 146.842609773155040m,
                            SoldierId = 27L
                        },
                        new
                        {
                            Id = 54L,
                            Latitude = 24.171127872265980m,
                            Longitude = -18.667386515448720m,
                            SoldierId = 27L
                        },
                        new
                        {
                            Id = 55L,
                            Latitude = 85.934826975854520m,
                            Longitude = -144.4230707046722640m,
                            SoldierId = 28L
                        },
                        new
                        {
                            Id = 56L,
                            Latitude = 40.888948898292120m,
                            Longitude = 40.389679728017280m,
                            SoldierId = 28L
                        },
                        new
                        {
                            Id = 57L,
                            Latitude = 89.363541936667320m,
                            Longitude = 36.138396712467960m,
                            SoldierId = 29L
                        },
                        new
                        {
                            Id = 58L,
                            Latitude = 26.628726487650300m,
                            Longitude = -75.981891929178960m,
                            SoldierId = 29L
                        },
                        new
                        {
                            Id = 59L,
                            Latitude = -79.5655036710256320m,
                            Longitude = -1.969818268506840m,
                            SoldierId = 30L
                        },
                        new
                        {
                            Id = 60L,
                            Latitude = -84.4928404047055980m,
                            Longitude = -30.059933708008080m,
                            SoldierId = 30L
                        });
                });

            modelBuilder.Entity("TrainingSimulation.Data.SoldierLocation", b =>
                {
                    b.HasOne("TrainingSimulation.Data.Soldier", "Soldier")
                        .WithMany("Locations")
                        .HasForeignKey("SoldierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Soldier");
                });

            modelBuilder.Entity("TrainingSimulation.Data.Soldier", b =>
                {
                    b.Navigation("Locations");
                });
#pragma warning restore 612, 618
        }
    }
}
